import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import ProvidersWrapper from "@/components/providers";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className} flex flex-col min-h-screen`}>
        <ProvidersWrapper>
          <div className="flex-grow">{children}</div>
          <footer className="mt-auto text-center text-gray-500 opacity-75 text-sm py-4">
            Created by Konstantinos Voskakis & Konstantinos Mavraidis
          </footer>
        </ProvidersWrapper>
      </body>
    </html>
  );
}
